# Generated by Django 5.1.7 on 2025-03-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
