version: "3.8"

services:
  db:
    image: postgres:14.7
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8089:8000"
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application

volumes:
  static_volume:
  media_volume:
  db: