# Generated by Django 5.1.7 on 2025-03-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_appointment_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
